### ISSUE TITLE
Attribute IFn

### ISSUE THREAD

**Issue by flyboarder** [hoplon/hoplon#190]
Extend keywords so they work as functions for DOM elements.

`(:test (div :test true))` -> `true`
`(:test (div :test true) false)` -> `false`

**Comment by flyboarder** [comment]
This would be appropriate inside a `doto` Without dropping to interop.

**Comment by thedavidmeister** [comment]
FYI https://github.com/hoplon/hoplon/issues/76

**Comment by thedavidmeister** [comment]
one thing that @micha pointed out in chat a while ago is that this simple example that looks very useful where `:test` is 1:1 on the input and output doesn't generalise super well.

because of the nature of functions that return a DOM element, this is pretty common too:

`(:foo (div :bar true :baz false))` -> `true`

i.e. the existence of any given attribute on the returned DOM element has no relation to the function arguments in general.

**Comment by flyboarder** [comment]
@thedavidmeister I see what you are saying, I might just keep this local to my project then, I have many cases where external js libs have data within elements, it is generally useful to query elements in a non-functional way as during runtime elements are mutable.

**Comment by thedavidmeister** [comment]
@flyboarder i'm not saying don't do it, i'm just saying we should be clear about what the use cases are so that if we run into snags down the line we can reference back to what the original goals were.

**Comment by flyboarder** [comment]
@thedavidmeister my original thought was getter/setter for attributes and listener/dispatcher for events, specifically for cases where mutation is required.

**Comment by thedavidmeister** [comment]
@flyboarder would something like this help? https://github.com/hoplon/hoplon/issues/176

**Comment by flyboarder** [comment]
@thedavidmeister possibly, it would probably be better to try implementing those first

**Comment by flyboarder** [comment]
Closing as this already works in the 7.1-proposal branch
