### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by seancorfield** [hoplon/hoplon#276]
I believe Hoplon was one of the "big" Boot users and although I see a `deps.edn` file in the repo, the README and the project template still focus on Boot -- and there seem to be quite a few problems trying to get Boot/Hoplon running on recent dependencies and O/S's?

Boot itself hasn't had a release in four years at this point and hasn't even had a source update in two years -- and it's problematic to run/build on recent JDK releases: https://github.com/Quantisan/docker-clojure/issues/192

**Comment by daveyarwood** [comment]
I think it's fair to consider both Boot and Hoplon to be unmaintained at this point.

If there is anyone in the community who would like to take over maintenance of these projects, I think that could be arranged. (I don't think I would have the authority to do that, but we could ask @micha @alandipert @flyboarder )

My own personal recommendation, if you're looking to get started with Hoplon, would be to use something React-based like Reagent, Re-frame or Helix, instead, as that's a more modern and well-supported setup for frontend ClojureScript code in 2023. And I would also recommend tools.deps / tools.build over Boot, as those projects are officially supported by the Clojure team.

We are still using Hoplon at Kevel, but we're working on migrating our frontend towards TypeScript + React, mostly for hiring reasons, but also in large part because Hoplon is unmaintained.

**Comment by alandipert** [comment]
@mynomoto recently [expressed desire in Slack](https://clojurians.slack.com/archives/C08BDAPRA/p1675189909218889) both to move tooling to shadow-cljs and take over as maintainer. As far as I can tell, he's already credentialed on GitHub and Clojars to do so; I've reached out to him to see if anything he needs is missing.

Based on my limited and probably dated knowledge shadow-cljs seems like the best build tooling to emphasize/document these days, but I'm curious if @seancorfield has other stuff in mind.

For what it's worth, and having used all manner of things since last using Hoplon, I can say confidently that irrespective of how you build your project with it, Hoplon itself is still architecturally sound and a fine choice of library for anyone building in ClojureScript.

Viva Hoplon! :crossed_swords:

**Comment by seancorfield** [comment]
I don't have strong opinions on ClojureScript tooling (but I lean slightly toward figwheel-main right now -- but may change my mind as I do more cljs :) ).

Good to know someone is interested in reinvigorating this project and moving it off Boot onto better-supported tooling!

**Comment by daveyarwood** [comment]
At Kevel, we use shadow-cljs to build our ClojureScript frontend, which includes Hoplon. shadow-cljs is fantastic!
