### ISSUE TITLE
Error loading page with :optimizations :none

### ISSUE THREAD

**Issue by micha** [hoplon/hoplon#42]

**Comment by ul** [comment]
Any plans to fix it? May be the same mechanism as used in boot2 `--unified` will help. Or, may be, it is “already fixed” because of upcoming boot2 hoplon support? It is quite painful to wait about 20sec on my laptop to recompile, especially after figwheel + optimizations none experience. I really like hoplon, because I think it simplifies some parts where react-based solutions make complications. But it could be even better ;-)

**Comment by micha** [comment]
fixed!
