### ISSUE TITLE
Road Map?

### ISSUE THREAD

**Issue by jab** [hoplon/hoplon#73]
TODO?: After a reader understands the use cases which Hoplon currently excels at, she may wonder if there is any planned support for $OTHER_USE_CASES (native, mobile, multi-page sites rather than just single-page (#70), anything else?).

Any interest in adding a "Road Map" page to the wiki capturing some of your thoughts on Hoplon Future?

**Comment by thedavidmeister** [comment]
@jab I'm not sure what the goal is here for documentation. For me "Road map" = "What will be built next?"

The question you're asking doesn't seem to be about the roadmap but about how Hoplon could address a few different common use-cases (or not).

**Comment by jab** [comment]
A road map would answer the question of not just what will be built next, but also what will be built after that. It helps the core developers communicate not just short-term priorities, but longer-term priorities future possibilities as well. See http://wiki.gimp.org/index.php/Roadmap for one example. https://github.com/hoplon/hoplon/milestones could be used to communicate this via future milestones (there's currently only a single milestone there, the current one).

**Comment by thedavidmeister** [comment]
OK, my feedback is that your OP is confusingly worded. It's really two different questions that might only co-incidentally or tangentially overlap.

The roadmap for Hoplon can still be a roadmap without addressing anything other than SPAs - for example, work around swapping out jQuery for a different backend here seems quite important to the future of Hoplon, yet has little to do with supporting a new set of use cases unrelated to SPA development https://github.com/hoplon/hoplon/issues/83

It's difficult to answer the "what is the roadmap?" question objectively if we have to manufacture it so that it also answers the question of "if there is any planned support for $OTHER_USE_CASES".

**Comment by flyboarder** [comment]
At the moment there are no clearly defined goals for the future of Hoplon, there might be future browser API's which we would like to include, however I think the scope is fairly well defined and nearly feature complete.

The README has been updated to include a `road map` badge which links to current/future milestones.

**Comment by thedavidmeister** [comment]
@flyboarder i think there's definitely an ongoing trend towards (in core at least):

- more extensibility in the protocols and element attributes
- fewer legacy browser hacks
- less dead/experimental code
- simpler APIs that leverage more native browser functionality
- less reliance on jQuery
- more automated test cases

i don't know if that counts as a "roadmap" but it is a set of goals for 7.1 and 7.2 for sure :)

**Comment by flyboarder** [comment]
@thedavidmeister I agree with many of these points, a few of them have been addressed already.

Resolved in `7.1`:
- fewer legacy browser hacks (old browser support removed)
- less reliance on jQuery (no longer required, however nothing equivalent yet)
- more automated test cases (you already covered most of the internals and public cases)
- following latest core trends (we use spec now too)

Should resolve in `7.2`:
- more extensibility in protocols and attributes (provided by new `elem!`)
- less dead/experimental code (removed!)
- simpler API’s (working on it...)
