### ISSUE TITLE
If `:fade-toggle` is false for the first element state, the element is visible

### ISSUE THREAD

**Issue by thedavidmeister** [hoplon/hoplon#94]
So, If I do this:

`(div :fade-toggle false "foo")`

The div is visible until I set it to true and then back to false.

Expected behaviour:

The div is invisible until I sent `:fade-toggle` to true, at which point it fades in.

Workaround:

`(div :css {:display "none"} :fade-toggle false "foo")`

**Comment by micha** [comment]
@thedavidmeister This is because it calls the jQuery fade method before the newly constructed div is in the dom. I think we can fix this whole class of issue by having a dynamic var, like `*constructing*` that is bound when new dom elements are being created. Then, when `*constructing*` is bound we can wrap the jQuery calls etc. in a `setTimeout(..., 0)` to have it delay applying those changes until the element is in the dom.

**Comment by thedavidmeister** [comment]
@micha any chance of a `constructing` cell, like `prerendering?` - i actually periodically run up against issues where i want to be able to only do something after the page has been properly constructed (3rd party libs, etc.)

**Comment by thedavidmeister** [comment]
oh, just discovered `when-dom`...

**Comment by flyboarder** [comment]
You could also try https://github.com/hoplon/hoplon/issues/137

**Comment by flyboarder** [comment]
Wrapped the jquery `:fade-toggle` in `when-dom` in `7.2` branch.
